'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Namespace CustomFilterPopup


    Partial Public Class WebForm1

        ''' <summary>
        ''' form1 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected form1 As Global.System.Web.UI.HtmlControls.HtmlForm

        ''' <summary>
        ''' ASPxPivotGrid1 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected ASPxPivotGrid1 As Global.DevExpress.Web.ASPxPivotGrid.ASPxPivotGrid

        ''' <summary>
        ''' fieldCompanyName control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected fieldCompanyName As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

        ''' <summary>
        ''' fieldOrderDate control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected fieldOrderDate As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

        ''' <summary>
        ''' fieldProductAmount control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected fieldProductAmount As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

        ''' <summary>
        ''' fieldProductName control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected fieldProductName As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

        ''' <summary>
        ''' NwindDataSource control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected NwindDataSource As Global.System.Web.UI.WebControls.AccessDataSource

        ''' <summary>
        ''' FilterPopup1 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected FilterPopup1 As Global.CustomFilterPopup.FilterPopup
    End Class
End Namespace
