'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Namespace CustomFilterPopup


    Partial Public Class FilterPopup

        ''' <summary>
        ''' ASPxPopupControl1 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected ASPxPopupControl1 As Global.DevExpress.Web.ASPxPopupControl

        ''' <summary>
        ''' ASPxGridView1 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected ASPxGridView1 As Global.DevExpress.Web.ASPxGridView

        ''' <summary>
        ''' buttonSelectAll control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected buttonSelectAll As Global.DevExpress.Web.ASPxButton

        ''' <summary>
        ''' buttonFilterInver control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected buttonFilterInver As Global.DevExpress.Web.ASPxButton

        ''' <summary>
        ''' buttonFilterOk control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected buttonFilterOk As Global.DevExpress.Web.ASPxButton

        ''' <summary>
        ''' buttonFilterCancel control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected buttonFilterCancel As Global.DevExpress.Web.ASPxButton
    End Class
End Namespace
